//  @ts-check

import { tanstackConfig } from "@tanstack/eslint-config"

export default [
  ...tanstackConfig,
  {
    rules: {
      "import/no-cycle": "off",
      "import/order": "off",
      "sort-imports": "off",
      "@typescript-eslint/array-type": "off",
      "@typescript-eslint/require-await": "off",
      "pnpm/json-enforce-catalog": "off",
    },
  },
  {
    ignores: [
      "eslint.config.js",
      "prettier.config.js",
      ".yarn/**",
      // Generated by Yarn, and rewritten wholesale on every install. `--fix`
      // otherwise edits them — it strips the `/* eslint-disable */` these ship
      // with — which lands unrelated churn in the next commit.
      ".pnp.cjs",
      ".pnp.loader.mjs",
    ],
  },
]
