/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StyleFlowRouteImport } from './routes/style-flow'
import { Route as LowResVideoRouteImport } from './routes/low-res-video'
import { Route as FutureTableRouteImport } from './routes/future-table'
import { Route as DitheringRouteImport } from './routes/dithering'
import { Route as CharacterFlowRouteImport } from './routes/character-flow'
import { Route as AntiAliasingRouteImport } from './routes/anti-aliasing'
import { Route as IndexRouteImport } from './routes/index'

const StyleFlowRoute = StyleFlowRouteImport.update({
  id: '/style-flow',
  path: '/style-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const LowResVideoRoute = LowResVideoRouteImport.update({
  id: '/low-res-video',
  path: '/low-res-video',
  getParentRoute: () => rootRouteImport,
} as any)
const FutureTableRoute = FutureTableRouteImport.update({
  id: '/future-table',
  path: '/future-table',
  getParentRoute: () => rootRouteImport,
} as any)
const DitheringRoute = DitheringRouteImport.update({
  id: '/dithering',
  path: '/dithering',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterFlowRoute = CharacterFlowRouteImport.update({
  id: '/character-flow',
  path: '/character-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const AntiAliasingRoute = AntiAliasingRouteImport.update({
  id: '/anti-aliasing',
  path: '/anti-aliasing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anti-aliasing': typeof AntiAliasingRoute
  '/character-flow': typeof CharacterFlowRoute
  '/dithering': typeof DitheringRoute
  '/future-table': typeof FutureTableRoute
  '/low-res-video': typeof LowResVideoRoute
  '/style-flow': typeof StyleFlowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anti-aliasing': typeof AntiAliasingRoute
  '/character-flow': typeof CharacterFlowRoute
  '/dithering': typeof DitheringRoute
  '/future-table': typeof FutureTableRoute
  '/low-res-video': typeof LowResVideoRoute
  '/style-flow': typeof StyleFlowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anti-aliasing': typeof AntiAliasingRoute
  '/character-flow': typeof CharacterFlowRoute
  '/dithering': typeof DitheringRoute
  '/future-table': typeof FutureTableRoute
  '/low-res-video': typeof LowResVideoRoute
  '/style-flow': typeof StyleFlowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anti-aliasing'
    | '/character-flow'
    | '/dithering'
    | '/future-table'
    | '/low-res-video'
    | '/style-flow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anti-aliasing'
    | '/character-flow'
    | '/dithering'
    | '/future-table'
    | '/low-res-video'
    | '/style-flow'
  id:
    | '__root__'
    | '/'
    | '/anti-aliasing'
    | '/character-flow'
    | '/dithering'
    | '/future-table'
    | '/low-res-video'
    | '/style-flow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AntiAliasingRoute: typeof AntiAliasingRoute
  CharacterFlowRoute: typeof CharacterFlowRoute
  DitheringRoute: typeof DitheringRoute
  FutureTableRoute: typeof FutureTableRoute
  LowResVideoRoute: typeof LowResVideoRoute
  StyleFlowRoute: typeof StyleFlowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/style-flow': {
      id: '/style-flow'
      path: '/style-flow'
      fullPath: '/style-flow'
      preLoaderRoute: typeof StyleFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/low-res-video': {
      id: '/low-res-video'
      path: '/low-res-video'
      fullPath: '/low-res-video'
      preLoaderRoute: typeof LowResVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/future-table': {
      id: '/future-table'
      path: '/future-table'
      fullPath: '/future-table'
      preLoaderRoute: typeof FutureTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dithering': {
      id: '/dithering'
      path: '/dithering'
      fullPath: '/dithering'
      preLoaderRoute: typeof DitheringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character-flow': {
      id: '/character-flow'
      path: '/character-flow'
      fullPath: '/character-flow'
      preLoaderRoute: typeof CharacterFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anti-aliasing': {
      id: '/anti-aliasing'
      path: '/anti-aliasing'
      fullPath: '/anti-aliasing'
      preLoaderRoute: typeof AntiAliasingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AntiAliasingRoute: AntiAliasingRoute,
  CharacterFlowRoute: CharacterFlowRoute,
  DitheringRoute: DitheringRoute,
  FutureTableRoute: FutureTableRoute,
  LowResVideoRoute: LowResVideoRoute,
  StyleFlowRoute: StyleFlowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
